import express from 'express';
import OpenAI from 'openai';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const app=express(); const __filename=fileURLToPath(import.meta.url); const __dirname=path.dirname(__filename);
const PORT=process.env.PORT||3000; const MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna'; const TOKEN=process.env.AGENT_TOKEN||'';
app.use(express.json({limit:'4mb'})); app.use(express.static(path.join(__dirname,'public')));
const SYSTEM=`You are Haroon AI Coding Agent. Understand Arabic and English. For Roblox build requests, do not make code the primary response. Return a JSON plan for a Studio-side agent. Allowed operations: create_instance, set_property, set_source, destroy, move. Use paths relative to game. Never claim changes are completed unless the agent reports them. JSON format: {"kind":"build","summary":"...","steps":[{"id":"1","title":"...","operation":"create_instance","className":"Folder","parent":"ReplicatedStorage","name":"...","properties":{}}]}. For normal programming questions, kind can be chat.`;
app.get('/health',(_q,r)=>r.json({ok:true,service:'Haroon AI Agent',model:MODEL}));
app.post('/api/plan',async(req,res)=>{try{if(!process.env.OPENAI_API_KEY)throw Error('OPENAI_API_KEY is not configured'); const {message,project}=req.body||{}; if(!message)return res.status(400).json({error:'message is required'}); const c=new OpenAI({apiKey:process.env.OPENAI_API_KEY}); const context=project?'\nPROJECT SNAPSHOT:\n'+JSON.stringify(project).slice(0,120000):''; const x=await c.responses.create({model:MODEL,instructions:SYSTEM,input:[{role:'user',content:String(message)+context}]}); const raw=x.output_text||''; let plan; try{plan=JSON.parse(raw)}catch{const m=raw.match(/\{[\s\S]*\}/); plan=m?JSON.parse(m[0]):{kind:'chat',summary:raw,steps:[]}} res.json({ok:true,plan,model:MODEL});}catch(e){console.error(e);res.status(500).json({error:e?.message||'AI request failed'})}});
app.post('/api/agent/event',(req,res)=>{if(TOKEN&&req.get('x-haroon-agent-token')!==TOKEN)return res.status(401).json({error:'Invalid agent token'}); console.log('[AGENT]',JSON.stringify(req.body)); res.json({ok:true})});
app.get('*',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`Haroon AI Agent running on ${PORT}`));
